name: Publish Docker image
on:
  push:
    branches: [ master ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Aliyun Docker Console
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: registry.cn-shanghai.aliyuncs.com
          dockerfile: ./github_action_test/Dockerfile
          repository: mkm/github-action
      - name: Push to  Docker Hub Console
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DockerHub_USERNAME }}
          password: ${{ secrets.DockerHub_PASSWORD }}
          dockerfile: ./github_action_test/Dockerfile
          repository: geekosh/github_action
          tags: github,test,github action
